# Generated by Django 3.1.6 on 2021-02-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('rg', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=80)),
                ('numero_endreco', models.IntegerField()),
                ('bairro', models.CharField(max_length=60)),
                ('cep', models.CharField(max_length=100)),
                ('data_registro', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pessoas',
                'managed': True,
            },
        ),
    ]
