# Generated by Django 3.1.6 on 2021-02-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=80)),
                ('dono', models.CharField(choices=[('PF', 'Pessoa física'), ('PF', 'Pessoa física')], max_length=100)),
            ],
            options={
                'db_table': 'empresas',
                'managed': True,
            },
        ),
    ]
